name: Deploy Snowflake Objects

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-linux_x86_64.bash
          bash snowsql-linux_x86_64.bash

      - name: Execute SQL Script
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWSQL_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

        run: |
          snowsql \
            -a RQVFAHA-BQ57083 \
            -u VASUDEVASFD1 \
            -p "Vasudeva.sfd@2" \
            -r ACCOUNTADMIN \
            -w COMPUTE_WH \
            -d MY_DB \
            -s MY_SCHEMA \
            -f sql/create_emp_practice_table.sql
