name: Deploy Snowflake Objects

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: snowflakedb/snowflake-cli-action@v1

      - name: Execute SQL
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

        run: |
          snow sql \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password "$SNOWFLAKE_PASSWORD" \
            --query "
            USE ROLE ACCOUNTADMIN;
            USE WAREHOUSE COMPUTE_WH;
            USE DATABASE MY_DB;
            USE SCHEMA MY_SCHEMA;
            "

          snow sql \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password "$SNOWFLAKE_PASSWORD" \
            --filename sql/create_emp_practice_table.sql
