name: Deploy Snowflake Objects

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: snowflakedb/snowflake-cli-action@v1.6
        with:
         cli-version: "3.16"

      - name: Execute SQL
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWSQL_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

        run: |
          snow sql \
            --account "$SNOWSQL_ACCOUNT" \
            --user "$SNOWSQL_USER" \
            --password "$SNOWSQL_PWD" \
            --query "
              USE ROLE $SNOWSQL_ROLE;
              USE WAREHOUSE $SNOWSQL_WAREHOUSE;
              USE DATABASE $SNOWSQL_DATABASE;
              USE SCHEMA $SNOWSQL_SCHEMA;
              "
          snow sql \
              --account "$SNOWSQL_ACCOUNT" \
              --user "$SNOWSQL_USER" \
              --password "$SNOWSQL_PWD" \
              --filename sql/create_emp_practice_table.sql
